def err_exit(err_msg):
    print(err_msg)
    exit()